version: 2
jobs:
  build:
    machine: true
    steps:
      - run: 
          name: git pull on ssh
          command: |
            ssh darammg@home.darammg.com -o StrictHostKeyChecking=no '
            cd ~/deploy/blog
            git pull
            rbenv local 2.6.3
            bundle exec jekyll build'
workflows:
  version: 2
  build:
    jobs:
      - build
        filters:
          branches:
            only: master
