version: 2
jobs:
  build:
    docker:        
      - image: circleci/node:latest
    steps:
      - run: 
          name: git pull on ssh
          command: |
            ssh -o StrictHostKeyChecking=no darammg@home.darammg.com '
            cd ~/deploy/blog
            git pull'
workflows:
  version: 2
  build:
    jobs:
      - build
